//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaNangZ.DbFirst.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string EntrySubject { get; set; }
        public string EntryContent { get; set; }
        public string AvatarLink { get; set; }
        public string Summarize { get; set; }
        public bool Actived { get; set; }
        public string StatusId { get; set; }
        public int OrderInHome { get; set; }
        public string InsBy { get; set; }
        public System.DateTime InsAt { get; set; }
        public string UpdBy { get; set; }
        public Nullable<System.DateTime> UpdAt { get; set; }
        public int ViewedCount { get; set; }
    }
}
