using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DaNangZ.UserService.UserService
{
    public interface IUserProfile<TUserId> where TUserId : struct
    {
        /// <summary>
        /// Id of the user profile.
        /// </summary>
        TUserId UserId { get; set; }

        /// <summary>
        /// Username of the user, it can be email for simplicity.
        /// </summary>
        string UserName { get; set; }

        /// <summary>
        /// User email.
        /// </summary>
        string Email { get; set; }

        /// <summary>
        /// <para>User display name, it can be full name, nickname, combination of first and last name, or generated by Username</para>
        /// <para>depends on the implementation but keep one field for simplicity.</para>
        /// <para>It will be useful to display name on the screen or user listing and friendly email address.</para>
        /// </summary>
        string DisplayName { get; set; }

        String StatusId { get; set; }

        DateTime UpdAt { get; set; }

        string UpdBy { get; set; }

        bool ReceiveEmail { get; set; }

        bool Active { get; set; }
    }
}
